Execution Result for model_h2o_training.py
--------------------------------------------------
=== Execution successful (attempt 1/3) in 12.23s ===
LOG_START:WARNING: Could not set Spanish locale, using default:LOG_END
LOG_START:DATA_SUMMARY
{"n_rows": 504, "n_cols": 2, "dtypes": {"fecha": "datetime64[ns]", "monto_total": "float64"}, "n_nulls": {"fecha": 26, "monto_total": 0}, "sample": [{"fecha": "2023-11-15 00:00:00", "monto_total": 8992.62}, {"fecha": "2023-11-16 00:00:00", "monto_total": 1354.86}, {"fecha": "2023-11-21 00:00:00", "monto_total": 15071.95}]}
LOG_END:DATA_SUMMARY
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "21.0.8" 2025-07-15; OpenJDK Runtime Environment (build 21.0.8+9-Debian-1); OpenJDK 64-Bit Server VM (build 21.0.8+9-Debian-1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.11/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmp5gsz10mr
  JVM stdout: /tmp/tmp5gsz10mr/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmp5gsz10mr/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.
Warning: Your H2O cluster version is (5 months and 7 days) old.  There may be a newer version available.
Please download and install the latest version from: https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html
--------------------------  ----------------------------------
H2O_cluster_uptime:         01 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.7
H2O_cluster_version_age:    5 months and 7 days
H2O_cluster_name:           H2O_from_python_unknownUser_qwwhjp
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1006 Mb
H2O_cluster_total_cores:    16
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.11.13 final
--------------------------  ----------------------------------
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
AutoML progress: |
15:48:56.67: User specified a validation frame with cross-validation still enabled. Please note that the models will still be validated using cross-validation only, the validation frame will be used to provide purely informative validation metrics on the trained models.

███████████████████████████████████████████████████████████████| (done) 100%
MODEL_PATH_START:/workspace/pipeline_c4817250-b02b-49ac-a00b-e7f87e432343/DRF_1_AutoML_1_20250904_154856:MODEL_PATH_END
METRICS_START:{"model_path": "/workspace/pipeline_c4817250-b02b-49ac-a00b-e7f87e432343/DRF_1_AutoML_1_20250904_154856", "metrics": {"rmse": 124644.7415162569, "mae": 94759.37151756165, "r2": 0.5057704683234732}, "rows_trained": 504, "n_features": 11, "training_time_secs": 10.181554317474365, "seed": 42, "h2o_version": "3.46.0.7", "dataset_size": 504}:METRICS_END
H2O session _sid_9d31 closed.
