Execution Result for model_h2o_training.py
--------------------------------------------------
Execution error (not missing module). Attempts: 1
/workspace/pipeline_3ee8ca9e-5834-4f88-a64d-e4a2ec2834dc/model_h2o_training.py:76: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(df[col], errors='coerce', dayfirst=True)
/workspace/pipeline_3ee8ca9e-5834-4f88-a64d-e4a2ec2834dc/model_h2o_training.py:76: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(df[col], errors='coerce', dayfirst=True)
LOG_START:DATA_SUMMARY
{"n_rows": 105830, "n_cols": 6, "dtypes": {"factura_nombre": "object", "factura_monto_total": "float64", "factura_total_descuentos": "float64", "factura_total_pagos": "float64", "vendedor_id": "float64", "cliente_nombre": "object"}, "n_nulls": {"factura_nombre": 0, "factura_monto_total": 0, "factura_total_descuentos": 0, "factura_total_pagos": 0, "vendedor_id": 79, "cliente_nombre": 570}, "sample": [{"factura_nombre": "/", "factura_monto_total": 0.0, "factura_total_descuentos": 0.0, "factura_total_pagos": 0.0, "vendedor_id": 1.0, "cliente_nombre": NaN}, {"factura_nombre": "/", "factura_monto_total": 0.0, "factura_total_descuentos": 0.0, "factura_total_pagos": 0.0, "vendedor_id": 2.0, "cliente_nombre": NaN}, {"factura_nombre": "/", "factura_monto_total": 0.0, "factura_total_descuentos": 0.0, "factura_total_pagos": 0.0, "vendedor_id": 2.0, "cliente_nombre": NaN}]}
LOG_END:DATA_SUMMARY
LOG_START:DATE_PARSE_ISSUE
Column:factura_monto_total
'Series' object has no attribute 'astitude'
LOG_END:DATE_PARSE_ISSUE
LOG_START:DATE_PARSE_ISSUE
Column:factura_total_descuentos
'Series' object has no attribute 'astitude'
LOG_END:DATE_PARSE_ISSUE
LOG_START:DATE_PARSE_ISSUE
Column:factura_total_pagos
'Series' object has no attribute 'astitude'
LOG_END:DATE_PARSE_ISSUE
LOG_START:DATE_PARSE_ISSUE
Column:vendedor_id
'Series' object has no attribute 'astitude'
LOG_END:DATE_PARSE_ISSUE
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "21.0.8" 2025-07-15; OpenJDK Runtime Environment (build 21.0.8+9-Debian-1); OpenJDK 64-Bit Server VM (build 21.0.8+9-Debian-1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.11/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmp8_225odd
  JVM stdout: /tmp/tmp8_225odd/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmp8_225odd/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.
Warning: Your H2O cluster version is (5 months and 12 days) old.  There may be a newer version available.
Please download and install the latest version from: https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html
--------------------------  ----------------------------------
H2O_cluster_uptime:         01 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.7
H2O_cluster_version_age:    5 months and 12 days
H2O_cluster_name:           H2O_from_python_unknownUser_ic10r2
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1.983 Gb
H2O_cluster_total_cores:    16
H2O_cluster_allowed_cores:  16
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.11.13 final
--------------------------  ----------------------------------
Parse progress: |███████████/usr/local/lib/python3.11/site-packages/h2o/estimators/estimator_base.py:192: RuntimeWarning: Dropping bad and constant columns: [factura_monto_total__is_weekend, factura_total_descuentos__year, factura_total_descuentos__is_month_start, factura_total_pagos__month, vendedor_id__year, vendedor_id__day, factura_total_pagos__year, factura_total_pagos__dayofweek, vendedor_id__is_weekend, factura_total_pagos__is_month_start, factura_total_pagos__day, factura_total_descuentos__dayofweek, factura_total_descuentos__is_weekend, vendedor_id__dayofweek, factura_total_descuentos__day, vendedor_id__month, factura_nombre, factura_total_descuentos, factura_total_descuentos__month, factura_total_pagos__is_weekend]
  warnings.warn(mesg["message"], RuntimeWarning)
█████████████████████████████████████████████████████| (done) 100%
LOG_START:UNSUPERVISED_LEARNING
Using Isolation Forest for anomaly detection
LOG_END:UNSUPERVISED_LEARNING
isolationforest Model Build progress: | (failed)
ERROR_START:Job with key $03017f00000132d4ffffffff$_a8e720e6187ae83a7599a60f83ae4b0e failed with an exception: java.lang.AssertionError stacktrace:  java.lang.AssertionError 	at hex.tree.DHistogram.init(DHistogram.java:350) 	at hex.tree.DHistogram.init(DHistogram.java:343) 	at hex.tree.ScoreBuildHistogram2$ComputeHistoThread.computeChunk(ScoreBuildHistogram2.java:427) 	at hex.tree.ScoreBuildHistogram2$ComputeHistoThread.map(ScoreBuildHistogram2.java:408) 	at water.LocalMR.compute2(LocalMR.java:89) 	at water.LocalMR.compute2(LocalMR.java:81) 	at water.LocalMR.compute2(LocalMR.java:81) 	at water.LocalMR.compute2(LocalMR.java:81) 	at water.LocalMR.compute2(LocalMR.java:81) 	at water.H2O$H2OCountedCompleter.compute(H2O.java:1704) 	at jsr166y.CountedCompleter.exec(CountedCompleter.java:468) 	at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263) 	at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:976) 	at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1479) 	at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) :ERROR_END
H2O session _sid_b9bf closed.

