Execution Result for train_model.py
--------------------------------------------------
=== Execution successful (attempt 1/3) in 108.89s ===
Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "21.0.8" 2025-07-15; OpenJDK Runtime Environment (build 21.0.8+9-Debian-1); OpenJDK 64-Bit Server VM (build 21.0.8+9-Debian-1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.11/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpv9lpjwyb
  JVM stdout: /tmp/tmpv9lpjwyb/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpv9lpjwyb/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.
Warning: Your H2O cluster version is (5 months and 7 days) old.  There may be a newer version available.
Please download and install the latest version from: https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html
--------------------------  ----------------------------------
H2O_cluster_uptime:         01 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.7
H2O_cluster_version_age:    5 months and 7 days
H2O_cluster_name:           H2O_from_python_unknownUser_xdzq45
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1.887 Gb
H2O_cluster_total_cores:    16
H2O_cluster_allowed_cores:  16
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.11.13 final
--------------------------  ----------------------------------
Reading CSV file...
Dataset shape: (504, 2)
First few rows:
          fecha  monto_total
0  15 nov. 2023      8992.62
1  16 nov. 2023      1354.86
2  21 nov. 2023     15071.95
3  22 nov. 2023     34009.92
4  23 nov. 2023     24072.84
Parsing Spanish dates...
Final dataset shape: (504, 10)
Date range: 2023-11-15 00:00:00 to 2025-08-07 00:00:00
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Target: monto_total
Features: ['year', 'month', 'day', 'day_of_week', 'day_of_year', 'week_of_year', 'is_weekend']
Train size: 504
Test size: 504
Starting H2O AutoML...
AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%
Traceback (most recent call last):
  File "/workspace/pipeline_580b3ebe-3c5f-4b2c-b27c-06394f9dc50c/train_model.py", line 120, in main
    predictions = best_model.predict(test)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h2o/model/model_base.py", line 332, in predict
    j = H2OJob(h2o.api("POST /4/Predictions/models/%s/frames/%s" % (self.model_id, test_data.frame_id), data = {'custom_metric_func': custom_metric_func}),
                                                                                   ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h2o/frame.py", line 414, in frame_id
    return self._frame()._ex._cache._id
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h2o/frame.py", line 584, in _frame
    self._ex._eager_frame()
  File "/usr/local/lib/python3.11/site-packages/h2o/expr.py", line 90, in _eager_frame
    self._eval_driver('frame')
  File "/usr/local/lib/python3.11/site-packages/h2o/expr.py", line 113, in _eval_driver
    exec_str = self._get_ast_str(top)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h2o/expr.py", line 151, in _get_ast_str
    exec_str = "({} {})".format(self._op, " ".join([ExprNode._arg_to_expr(ast) for ast in self._children]))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h2o/expr.py", line 151, in <listcomp>
    exec_str = "({} {})".format(self._op, " ".join([ExprNode._arg_to_expr(ast) for ast in self._children]))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h2o/expr.py", line 189, in _arg_to_expr
    assert start >= 0 and step >= 1 and (math.isnan(stop) or stop >= start + step)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
AutoML Leaderboard:
model_id                                                   rmse          mse      mae      rmsle    mean_residual_deviance
StackedEnsemble_BestOfFamily_1_AutoML_1_20250904_144456  114603  1.31338e+10  76760.9  nan                     1.31338e+10
GBM_grid_1_AutoML_1_20250904_144456_model_2              116313  1.35287e+10  78229.9  nan                     1.35287e+10
StackedEnsemble_AllModels_1_AutoML_1_20250904_144456     116386  1.35457e+10  77707.9  nan                     1.35457e+10
GBM_4_AutoML_1_20250904_144456                           116496  1.35713e+10  77567.1  nan                     1.35713e+10
GBM_2_AutoML_1_20250904_144456                           116624  1.36011e+10  78170.5  nan                     1.36011e+10
GBM_3_AutoML_1_20250904_144456                           116761  1.36331e+10  78261.5  nan                     1.36331e+10
DRF_1_AutoML_1_20250904_144456                           119419  1.42608e+10  79809      2.65938               1.42608e+10
DeepLearning_1_AutoML_1_20250904_144456                  120979  1.4636e+10   83180.7  nan                     1.4636e+10
GBM_grid_1_AutoML_1_20250904_144456_model_1              121792  1.48334e+10  81953.9  nan                     1.48334e+10
GBM_5_AutoML_1_20250904_144456                           121834  1.48436e+10  82658.9  nan                     1.48436e+10
[10 rows x 6 columns]

Best model: StackedEnsemble_BestOfFamily_1_AutoML_1_20250904_144456
Error occurred: 
H2O session _sid_9088 closed.

Execution result: {'status': 'error', 'message': ''}
